version: '3'

services:
  web:
    image: nauticas/web:1.0
    volumes:
      - ./Apps:/var/www
    ports:
      - "80:80"
    links:
      - app

  app:
    image: nauticas/app:1.0
    volumes:
      - ./Apps:/var/www
    links:
      - db
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"

  db:
    image: mariadb:10
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=krs"
    volumes:
      - ./Database:/var/lib
    ports:
      - "3306:3306"
      
